from __future__ import annotations

import argparse
import os
import subprocess
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
OUTPUT_PATH = ROOT / "deploy" / "backend_publish_readiness_gate.md"
IGNORED_GENERATED_PATHS = {
    "deploy/backend_launch_package.md",
    "deploy/backend_publish_readiness_gate.md",
    "deploy/render_env_runbook.md",
    "security/data_governance_runbook.md",
}


def run(command: list[str]) -> tuple[bool, str]:
    env = os.environ.copy()
    env["PYTHONPATH"] = str(ROOT)
    result = subprocess.run(command, cwd=ROOT, env=env, text=True, capture_output=True, check=False)
    return result.returncode == 0, f"{result.stdout}{result.stderr}".strip()


def git_output(args: list[str]) -> str:
    ok, output = run(["git", *args])
    return output if ok else ""


def source_changes() -> list[str]:
    status = git_output(["status", "--short"])
    changes = []
    for line in status.splitlines():
        if not line.strip():
            continue
        parts = line.strip().split(maxsplit=1)
        changed_path = parts[1] if len(parts) == 2 else line[3:].strip()
        if changed_path not in IGNORED_GENERATED_PATHS:
            changes.append(line)
    return changes


def row(label: str, passed: bool, detail: str) -> str:
    return f"| {label} | {'Pass' if passed else 'Blocked'} | {detail} |"


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate the CareWise backend publish gate.")
    parser.add_argument(
        "--base-url",
        default="",
        help="Deployed API URL to smoke-test, for example https://carewise-api.onrender.com",
    )
    args = parser.parse_args()

    OUTPUT_PATH.write_text(
        "# CareWise Backend Publish Readiness Gate\n\n"
        "Generated by `python3 scripts/backend_publish_gate.py`.\n\n"
        "**BLOCKED BEFORE REAL PATIENT DATA**\n\n"
        "Regenerating deployed checks, including the Deployed synthetic smoke test.\n"
        "CareWise is not a medical diagnosis tool.\n"
        "Do not trust this placeholder for production launch decisions.\n"
    )

    branch = git_output(["status", "--short", "--branch"]).splitlines()[0]
    ahead = "[ahead " in branch
    changes = source_changes()
    static_ok, static_output = run(["python3", "tests/static_readiness_check.py"])
    storage_ok, storage_output = run(["python3", "scripts/check_storage.py"])

    smoke_ok = False
    smoke_output = "Not run. Pass --base-url https://YOUR-API-URL to test the deployed backend."
    if args.base_url:
        smoke_ok, smoke_output = run(
            ["python3", "scripts/smoke_test_deploy.py", "--base-url", args.base_url]
        )

    automated_gates = [
        (
            "No uncommitted source changes",
            not changes,
            "Working tree has no uncommitted source changes."
            if not changes
            else f"{len(changes)} source change(s) need to be committed or intentionally parked.",
        ),
        (
            "Backend commits pushed to GitHub",
            not ahead,
            "Local backend branch is not ahead of origin."
            if not ahead
            else "Local backend commits still need to be pushed.",
        ),
        (
            "Static backend readiness",
            static_ok,
            "Static readiness check passed."
            if static_ok
            else static_output.replace("\n", " ")[:500],
        ),
        (
            "Storage configuration check",
            storage_ok,
            "Storage check passed with current environment."
            if storage_ok
            else storage_output.replace("\n", " ")[:500],
        ),
        (
            "Deployed synthetic smoke test",
            smoke_ok,
            "Deployment smoke test passed with synthetic data and cleanup."
            if smoke_ok
            else smoke_output.replace("\n", " ")[:500],
        ),
    ]

    engineering_passed = all(item[1] for item in automated_gates)
    decision = "MANUAL APPROVALS STILL REQUIRED" if engineering_passed else "BLOCKED BEFORE REAL PATIENT DATA"

    report = f"""# CareWise Backend Publish Readiness Gate

Generated by `python3 scripts/backend_publish_gate.py`.

## Decision

**{decision}**

CareWise backend must not be trusted for real patient data until the deployed API smoke test, private storage verification, privacy export/deletion checks, legal/privacy review, security review, and clinician review are complete. CareWise explains uploaded reports in simple language for education and visit preparation. It is not a medical diagnosis tool, does not provide emergency care, and must not claim diagnosis, cure, prescription, treatment, disease prevention, insurance approval, or exact out-of-pocket costs.

## Automated Gates

| Gate | Status | Detail |
| --- | --- | --- |
{chr(10).join(row(*item) for item in automated_gates)}

## Required Command Order

```bash
python3 tests/static_readiness_check.py
python3 scripts/generate_render_env_runbook.py
python3 scripts/generate_data_governance_runbook.py
python3 scripts/check_storage.py
python3 scripts/backend_publish_gate.py --base-url https://YOUR-API-URL
```

The publish gate runs `scripts/smoke_test_deploy.py` against the deployed API when `--base-url` is supplied.

## Manual Release Gates

- [ ] Render production environment variables match `deploy/render_env_runbook.md`.
- [ ] Durable storage is Cloudflare R2 or AWS S3 with private bucket access only.
- [ ] Privacy export does not expose private storage URLs.
- [ ] Account deletion removes database records and attempts stored report object deletion.
- [ ] Legal/privacy reviewer approves Privacy Policy, Terms, Medical Disclaimer, and Data Deletion pages.
- [ ] Licensed clinician approves report explanation wording and high-risk escalation language.
- [ ] Backup/restore, retention, audit-log, and incident-response policies are approved.
- [ ] Load tests are run before marketing traffic, investor demos with live users, or public release.

## Stop Immediately If

- Real patient data appears in logs, screenshots, tickets, analytics, docs, or test evidence.
- Private storage URLs, access tokens, database URLs, API keys, Render secrets, R2/S3 keys, or Stripe secrets are exposed.
- AI wording implies diagnosis, treatment, cure, prescription, emergency support, disease prevention, or insurance guarantees.
- The deployed smoke test requires real patient information to pass.

## Latest Smoke Output

```text
{smoke_output[:3000]}
```
"""

    OUTPUT_PATH.write_text(report)
    print(f"CareWise backend publish readiness gate written to {OUTPUT_PATH.relative_to(ROOT)}.")
    return 0 if engineering_passed else 1


if __name__ == "__main__":
    raise SystemExit(main())
