from __future__ import annotations

import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
OUTPUT_PATH = ROOT / "security" / "data_governance_runbook.md"


def read_text(relative_path: str) -> str:
    return (ROOT / relative_path).read_text()


def route_exists(source: str, route: str) -> bool:
    return route in source


def main() -> None:
    privacy_route = read_text("app/api/routes/privacy.py")
    storage_service = read_text("app/services/storage.py")
    privacy_review = read_text("security/privacy_review.md")

    checks = [
        ("Privacy export summary endpoint exists", route_exists(privacy_route, '"/me/export-summary"')),
        ("Full privacy export endpoint exists", route_exists(privacy_route, '"/me/export"')),
        ("Data deletion request endpoint exists", route_exists(privacy_route, '"/me/delete-request"')),
        ("Self-service delete endpoint exists", route_exists(privacy_route, '"/me"')),
        ("Stored report file deletion is attempted", "delete_stored_file(report.storage_key)" in privacy_route),
        ("S3/R2 object deletion helper exists", "delete_object" in storage_service),
        ("Retention schedule is called out in privacy review", "Data retention schedule" in privacy_review),
        ("Backup restore drills are called out in privacy review", "Backup restore drills" in privacy_review),
    ]
    endpoints = sorted(set(re.findall(r'@router\.(?:get|post|delete)\("([^"]+)"', privacy_route)))
    endpoint_lines = "\n".join(f"- `{match}`" for match in endpoints)

    report = f"""# CareWise Data Governance Runbook

Generated by `python3 scripts/generate_data_governance_runbook.py`.

Use this before collecting real patient data. This is an operational checklist, not legal advice. Healthcare counsel, privacy counsel, security engineering, and clinical reviewers must approve final policies.

## Local Capability Checks

{chr(10).join(f"- [{'x' if passed else ' '}] {label}" for label, passed in checks)}

## Data Export Workflow

1. User requests export from the app Legal screen or support flow.
2. Use `GET /privacy/me/export-summary` when showing counts in-product.
3. Use `GET /privacy/me/export` for full account export.
4. Confirm exports do not include private storage URLs.
5. Confirm exports use synthetic test data during QA.

## Data Deletion Workflow

1. User submits `POST /privacy/me/delete-request` or self-service `DELETE /privacy/me`.
2. Backend attempts to delete stored report objects before deleting database rows.
3. Backend deletes patient records, reports, analyses, medications, intakes, care plans, lab trends, subscriptions, notifications, auth tokens, and user account records.
4. Operators must reconcile any object-storage deletion failures from audit/support evidence.
5. Validate deletion using a synthetic test account before public launch.

## Backup And Retention Policy To Approve

- [ ] Define database backup frequency and retention period.
- [ ] Define object-storage backup/versioning policy.
- [ ] Define deletion behavior for backups and legal holds.
- [ ] Define audit-event retention and who can access it.
- [ ] Define regional privacy and residency requirements.
- [ ] Run a backup restore drill before real patient use.
- [ ] Document who approves deletion exceptions.

## Verification Commands

Run these with synthetic data only:

```bash
python3 scripts/smoke_test_deploy.py --base-url https://YOUR-API-URL
python3 scripts/check_storage.py
```

Smoke test must confirm:

- Privacy export summary counts include created records.
- Full privacy export includes expected synthetic records.
- Private storage URLs are not exposed in exports.
- Self-service deletion returns `deleted`.
- Smoke account cleanup completes.

## Do Not Do

- Do not use real patient data in governance tests.
- Do not store health report text in logs.
- Do not expose private storage URLs in mobile or web clients.
- Do not promise immediate deletion from backups until legal and retention policy explicitly supports it.
- Do not describe CareWise as a diagnosis, cure, prescription, emergency, or insurance guarantee product.

## Source Endpoints Found

{endpoint_lines}
"""

    OUTPUT_PATH.write_text(report)
    print(f"CareWise data governance runbook written to {OUTPUT_PATH.relative_to(ROOT)}.")


if __name__ == "__main__":
    main()
