from __future__ import annotations

import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
OUTPUT_PATH = ROOT / "deploy" / "render_env_runbook.md"


def read_text(relative_path: str) -> str:
    return (ROOT / relative_path).read_text()


def parse_env_example(text: str) -> dict[str, str]:
    values: dict[str, str] = {}
    for line in text.splitlines():
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        values[key.strip()] = value.strip()
    return values


def parse_render_env_keys(text: str) -> list[str]:
    return re.findall(r"key:\s*([A-Z0-9_]+)", text)


def main() -> None:
    env_values = parse_env_example(read_text(".env.production.example"))
    render_keys = parse_render_env_keys(read_text("render.yaml"))

    required_for_render = [
        "CAREWISE_ENV",
        "CAREWISE_DATABASE_URL",
        "CAREWISE_JWT_SECRET",
        "CAREWISE_FIELD_ENCRYPTION_KEY",
        "CAREWISE_ALLOWED_ORIGINS",
        "CAREWISE_STORAGE_BACKEND",
        "CAREWISE_S3_BUCKET",
        "CAREWISE_S3_REGION",
        "AWS_ACCESS_KEY_ID",
        "AWS_SECRET_ACCESS_KEY",
    ]
    optional_before_launch = [
        "CAREWISE_S3_ENDPOINT_URL",
        "CAREWISE_OPENAI_API_KEY",
        "CAREWISE_OPENAI_OCR_MODEL",
        "CAREWISE_STRIPE_SECRET_KEY",
        "CAREWISE_STRIPE_SUCCESS_URL",
        "CAREWISE_STRIPE_CANCEL_URL",
        "CAREWISE_SMTP_HOST",
        "CAREWISE_SMTP_USERNAME",
        "CAREWISE_SMTP_PASSWORD",
        "CAREWISE_SMTP_FROM_EMAIL",
    ]

    report = f"""# CareWise Render Environment Runbook

Generated by `python3 scripts/generate_render_env_runbook.py`.

Use this when configuring Render. Do not paste actual secret values into this file or commit secrets to Git.

## Render Blueprint Env Vars

These keys are declared in `render.yaml`:

{chr(10).join(f"- `{key}`" for key in render_keys)}

## Required Before Production Deploy

{chr(10).join(f"- [ ] `{key}`" for key in required_for_render)}

## Optional But Expected Before Public Launch

{chr(10).join(f"- [ ] `{key}`" for key in optional_before_launch)}

## Suggested Values

- `CAREWISE_ENV`: `production`
- `CAREWISE_STORAGE_BACKEND`: `s3`
- `CAREWISE_S3_REGION`: `us-east-1` for Cloudflare R2 compatibility unless your provider requires another region.
- `CAREWISE_ALLOWED_ORIGINS`: deployed frontend domain only, for example `https://carewise-frontend.onrender.com`.
- `CAREWISE_S3_ENDPOINT_URL`: required for Cloudflare R2, usually the account-specific R2 endpoint.

## Post-Deploy Verification

Run these after saving Render env vars and redeploying:

```bash
python3 scripts/check_storage.py
python3 scripts/smoke_test_deploy.py --base-url https://YOUR-API-URL
```

Then check:

- `/ready` returns `ready`.
- `/features` shows `durable_storage: true`.
- `/features` shows `storage_ready: true`.
- Smoke test creates only synthetic data and cleans itself up.

## Safety Notes

- Do not put OpenAI keys, R2 keys, AWS keys, Stripe keys, SMTP passwords, or Render database URLs in mobile/web frontend code.
- Do not use real patient reports while testing environment setup.
- Do not submit to app stores until storage, deletion, privacy export, and smoke tests pass.
- Do not describe CareWise as a diagnosis, cure, prescription, emergency, or insurance guarantee product.

## Env Example Coverage

{chr(10).join(f"- [{'x' if key in env_values else ' '}] `{key}` documented in `.env.production.example`" for key in required_for_render + optional_before_launch)}
"""

    OUTPUT_PATH.write_text(report)
    print(f"CareWise Render env runbook written to {OUTPUT_PATH.relative_to(ROOT)}.")


if __name__ == "__main__":
    main()
