from __future__ import annotations

import json
import subprocess
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
OUTPUT_PATH = ROOT / "deploy" / "backend_launch_package.md"


def read_text(relative_path: str) -> str:
    return (ROOT / relative_path).read_text()


def run(command: list[str]) -> tuple[bool, str]:
    result = subprocess.run(command, cwd=ROOT, text=True, capture_output=True, check=False)
    return result.returncode == 0, f"{result.stdout}{result.stderr}".strip()


def checkbox(done: bool, text: str) -> str:
    return f"- [{'x' if done else ' '}] {text}"


def main() -> None:
    render_yaml = read_text("render.yaml")
    env_example = read_text(".env.production.example")
    readme = read_text("README.md")

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(
        "# CareWise Backend Launch Package\n\n"
        "## Required Production Secrets\n\n"
        "Regenerating.\n\n"
        "## Deploy Verification Commands\n\n"
        "Regenerating.\n\n"
        "## Manual Healthcare Blockers\n\n"
        "Regenerating.\n\n"
        "Do not describe CareWise as a diagnosis product.\n"
    )

    static_ok, static_output = run(["python3", "tests/static_readiness_check.py"])
    storage_script_exists = (ROOT / "scripts" / "check_storage.py").exists()
    smoke_script_exists = (ROOT / "scripts" / "smoke_test_deploy.py").exists()
    dockerfile = read_text("Dockerfile")

    checks = [
        checkbox("type: web" in render_yaml, "Render web service is declared"),
        checkbox("carewise-postgres" in render_yaml, "Render PostgreSQL service is declared"),
        checkbox("CAREWISE_JWT_SECRET" in render_yaml, "JWT secret is configured as a required Render env var"),
        checkbox(
            "CAREWISE_FIELD_ENCRYPTION_KEY" in render_yaml,
            "Field encryption key is configured as a required Render env var",
        ),
        checkbox("CAREWISE_STORAGE_BACKEND" in env_example, "Storage backend env var is documented"),
        checkbox("CAREWISE_S3_BUCKET" in env_example, "S3/R2 bucket env var is documented"),
        checkbox("CAREWISE_OPENAI_API_KEY" in env_example, "OpenAI API key stays backend-only"),
        checkbox("python -m app.db.migrate" in dockerfile, "Container runs migrations before API start"),
        checkbox(storage_script_exists, "Storage configuration check script exists"),
        checkbox(smoke_script_exists, "Deployment smoke-test script exists"),
        checkbox(static_ok, "Static backend readiness check passes"),
        checkbox("not cleared for real patient use" in readme.lower(), "README keeps healthcare launch warning"),
    ]

    report = f"""# CareWise Backend Launch Package

Generated by `python3 scripts/generate_backend_launch_package.py`.

## Automated Local Checks

{chr(10).join(checks)}

## Required Production Secrets

Set these only in Render or the production secret manager. Do not commit them.

- `CAREWISE_JWT_SECRET`
- `CAREWISE_FIELD_ENCRYPTION_KEY`
- `CAREWISE_DATABASE_URL`
- `CAREWISE_ALLOWED_ORIGINS`
- `CAREWISE_STORAGE_BACKEND`
- `CAREWISE_S3_BUCKET`
- `CAREWISE_S3_REGION`
- `CAREWISE_S3_ENDPOINT_URL` when using Cloudflare R2
- `AWS_ACCESS_KEY_ID`
- `AWS_SECRET_ACCESS_KEY`
- `CAREWISE_OPENAI_API_KEY` if OCR/AI analysis is enabled
- `CAREWISE_STRIPE_SECRET_KEY` only when real subscription checkout is enabled

## Deploy Verification Commands

Run these before trusting a deployment:

```bash
python3 tests/static_readiness_check.py
python3 scripts/check_storage.py
python3 scripts/smoke_test_deploy.py --base-url https://YOUR-API-URL
```

Expected deployed health:

- `/health` returns healthy status.
- `/ready` returns ready after database and storage are configured.
- `/features` shows durable storage ready before real report uploads.
- Smoke test uses only synthetic data and cleans up the smoke account.

## Manual Healthcare Blockers

- [ ] Legal/privacy review approves Privacy Policy, Terms, Disclaimer, and Data Deletion flows.
- [ ] Clinician reviewer approves high-risk and non-diagnostic wording.
- [ ] Render/R2/S3 storage is private and file URLs are not publicly exposed.
- [ ] OpenAI, storage, and payment processors are documented in privacy forms.
- [ ] Backups, retention, deletion, and audit-log policies are approved before real patient use.
- [ ] Load tests are run before marketing traffic or investor demos with live users.

## Do Not Do

- Do not store health data in logs.
- Do not expose private bucket URLs in frontend code.
- Do not put OpenAI, Render, Stripe, R2, AWS, Apple, Google, or GitHub secrets in Git.
- Do not describe CareWise as a diagnosis, cure, prescription, emergency, or insurance guarantee product.

## Static Check Output

```json
{json.dumps(json.loads(static_output), indent=2) if static_ok else static_output}
```
"""

    OUTPUT_PATH.write_text(report)
    print(f"CareWise backend launch package written to {OUTPUT_PATH.relative_to(ROOT)}.")


if __name__ == "__main__":
    main()
